CREATE DATABASE IF NOT EXISTS energostat_db;
USE energostat_db;

-- COUNTRY table
CREATE TABLE IF NOT EXISTS COUNTRY (
    countryId VARCHAR(3) PRIMARY KEY,
    countryName VARCHAR(100) NOT NULL UNIQUE,
    flagCode VARCHAR(3) NOT NULL UNIQUE
) ENGINE = InnoDB;

-- APP_USER table
CREATE TABLE IF NOT EXISTS APP_USER (
    userId INT AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    countryId VARCHAR(3),
    dataId INT, -- just an integer for now
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (countryId) REFERENCES COUNTRY(countryId)
) ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS ENERGY_DATA (
    dataId INT AUTO_INCREMENT PRIMARY KEY,
    year VARCHAR(4) NOT NULL,
    population INT NOT NULL,
    populationInMillions FLOAT NOT NULL,
    energyConsumption FLOAT NOT NULL,
    energyPerCapita FLOAT NOT NULL,
    countryId VARCHAR(3),
    userId INT,  -- integer
    FOREIGN KEY (countryId) REFERENCES COUNTRY(countryId)
) ENGINE = InnoDB;

ALTER TABLE APP_USER
ADD CONSTRAINT fk_user_data FOREIGN KEY (dataId) REFERENCES ENERGY_DATA(dataId);

ALTER TABLE ENERGY_DATA
ADD CONSTRAINT fk_energy_user FOREIGN KEY (userId) REFERENCES APP_USER(userId);


-- Initial data for COUNTRY table TOP 100 most populous countries
INSERT IGNORE INTO COUNTRY (countryId, countryName, flagCode) VALUES
('RUS', 'Russia', 'RU'),
('CAN', 'Canada', 'CA'),
('CHN', 'China', 'CN'),
('USA', 'United States', 'US'),
('BRA', 'Brazil', 'BR'),
('AUS', 'Australia', 'AU'),
('IND', 'India', 'IN'),
('ARG', 'Argentina', 'AR'),
('KAZ', 'Kazakhstan', 'KZ'),
('DZA', 'Algeria', 'DZ'),
('COD', 'Democratic Republic of the Congo', 'CD'),
('GRL', 'Greenland', 'GL'),
('SAU', 'Saudi Arabia', 'SA'),
('MEX', 'Mexico', 'MX'),
('IDN', 'Indonesia', 'ID'),
('SDN', 'Sudan', 'SD'),
('LBY', 'Libya', 'LY'),
('IRN', 'Iran', 'IR'),
('MNG', 'Mongolia', 'MN'),
('PER', 'Peru', 'PE'),
('TCD', 'Chad', 'TD'),
('NIG', 'Niger', 'NE'),
('AGO', 'Angola', 'AO'),
('MLI', 'Mali', 'ML'),
('ZAF', 'South Africa', 'ZA'),
('COL', 'Colombia', 'CO'),
('ETH', 'Ethiopia', 'ET'),
('BOL', 'Bolivia', 'BO'),
('MRT', 'Mauritania', 'MR'),
('EGY', 'Egypt', 'EG'),
('TZA', 'Tanzania', 'TZ'),
('NGA', 'Nigeria', 'NG'),
('VEN', 'Venezuela', 'VE'),
('NAM', 'Namibia', 'NA'),
('PAK', 'Pakistan', 'PK'),
('MOZ', 'Mozambique', 'MZ'),
('TUR', 'Turkey', 'TR'),
('CHL', 'Chile', 'CL'),
('ZMB', 'Zambia', 'ZM'),
('MMR', 'Myanmar', 'MM'),
('AFG', 'Afghanistan', 'AF'),
('FRA', 'France', 'FR'),
('SOM', 'Somalia', 'SO'),
('CAF', 'Central African Republic', 'CF'),
('UKR', 'Ukraine', 'UA'),
('MDG', 'Madagascar', 'MG'),
('BOT', 'Botswana', 'BW'),
('KEN', 'Kenya', 'KE'),
('YEM', 'Yemen', 'YE'),
('THA', 'Thailand', 'TH'),
('ESP', 'Spain', 'ES'),
('TKM', 'Turkmenistan', 'TM'),
('CMR', 'Cameroon', 'CM'),
('PNG', 'Papua New Guinea', 'PG'),
('SWE', 'Sweden', 'SE'),
('UZB', 'Uzbekistan', 'UZ'),
('MAR', 'Morocco', 'MA'),
('IRQ', 'Iraq', 'IQ'),
('PAR', 'Paraguay', 'PY'),
('ZWE', 'Zimbabwe', 'ZW'),
('JPN', 'Japan', 'JP'),
('DEU', 'Germany', 'DE'),
('CIV', "Côte d'Ivoire", 'CI'),
('PHL', 'Philippines', 'PH'),
('CUB', 'Cuba', 'CU'),
('LAO', "Lao People's Democratic Republic", 'LA'),
('GAB', 'Gabon', 'GA'),
('ECU', 'Ecuador', 'EC'),
('GTM', 'Guatemala', 'GT'),
('GUY', 'Guyana', 'GY'),
('ROU', 'Romania', 'RO'),
('GHA', 'Ghana', 'GH'),
('POL', 'Poland', 'PL'),
('OMN', 'Oman', 'OM'),
('ITA', 'Italy', 'IT'),
('BFA', 'Burkina Faso', 'BF'),
('NZL', 'New Zealand', 'NZ'),
('GAB', 'Gabon', 'GA'),
('GNB', 'Guinea-Bissau', 'GW'),
('UGA', 'Uganda', 'UG'),
('UKR', 'Ukraine', 'UA'),
('UZB', 'Uzbekistan', 'UZ'),
('VEN', 'Venezuela', 'VE'),
('VNM', 'Vietnam', 'VN'),
('YEM', 'Yemen', 'YE'),
('ZMB', 'Zambia', 'ZM'),
('ZWE', 'Zimbabwe', 'ZW'),
('AFG', 'Afghanistan', 'AF'),
('ALB', 'Albania', 'AL'),
('AND', 'Andorra', 'AD'),
('AGO', 'Angola', 'AO'),
('ATG', 'Antigua and Barbuda', 'AG'),
('ARG', 'Argentina', 'AR'),
('ARM', 'Armenia', 'AM'),
('AUS', 'Australia', 'AU'),
('AUT', 'Austria', 'AT'),
('AZE', 'Azerbaijan', 'AZ'),
('BHS', 'Bahamas', 'BS'),
('BHR', 'Bahrain', 'BH'),
('BGD', 'Bangladesh', 'BD'),
('BRB', 'Barbados', 'BB'),
('BLR', 'Belarus', 'BY'),
('BEL', 'Belgium', 'BE'),
('BLZ', 'Belize', 'BZ'),
('BEN', 'Benin', 'BJ'),
('BTN', 'Bhutan', 'BT'),
('BOL', 'Bolivia', 'BO'),
('BIH', 'Bosnia and Herzegovina', 'BA'),
('BWA', 'Botswana', 'BW'),
('BRA', 'Brazil', 'BR'),
('BRN', 'Brunei Darussalam', 'BN'),
('BGR', 'Bulgaria', 'BG'),
('BFA', 'Burkina Faso', 'BF'),
('BDI', 'Burundi', 'BI'),
('CPV', 'Cabo Verde', 'CV'),
('KHM', 'Cambodia', 'KH'),
('CMR', 'Cameroon', 'CM'),
('CAN', 'Canada', 'CA'),
('CAF', 'Central African Republic', 'CF'),
('TCD', 'Chad', 'TD'),
('CHL', 'Chile', 'CL'),
('CHN', 'China', 'CN'),
('COL', 'Colombia', 'CO'),
('COM', 'Comoros', 'KM'),
('COG', 'Congo', 'CG'),
('COD', 'Congo, Democratic Republic of the', 'CD'),
('CRI', 'Costa Rica', 'CR'),
('CIV', "Côte d'Ivoire", 'CI'),
('HRV', 'Croatia', 'HR'),
('CUB', 'Cuba', 'CU'),
('CYP', 'Cyprus', 'CY'),
('CZE', 'Czech Republic', 'CZ'),
('DNK', 'Denmark', 'DK'),
('DJI', 'Djibouti', 'DJ'),
('DMA', 'Dominica', 'DM'),
('DOM', 'Dominican Republic', 'DO'),
('ECU', 'Ecuador', 'EC'),
('EGY', 'Egypt', 'EG'),
('SLV', 'El Salvador', 'SV'),
('GNQ', 'Equatorial Guinea', 'GQ'),
('ERI', 'Eritrea', 'ER'),
('EST', 'Estonia', 'EE'),
('SWZ', 'Eswatini', 'SZ'),
('ETH', 'Ethiopia', 'ET'),
('FJI', 'Fiji', 'FJ'),
('FIN', 'Finland', 'FI'),
('FRA', 'France', 'FR'),
('GAB', 'Gabon', 'GA'),
('GMB', 'Gambia', 'GM'),
('GEO', 'Georgia', 'GE'),
('DEU', 'Germany', 'DE'),
('GHA', 'Ghana', 'GH'),
('GRC', 'Greece', 'GR'),
('GRD', 'Grenada', 'GD'),
('GTM', 'Guatemala', 'GT'),
('GIN', 'Guinea', 'GN'),
('GNB', 'Guinea-Bissau', 'GW'),
('GUY', 'Guyana', 'GY'),
('HTI', 'Haiti', 'HT'),
('HND', 'Honduras', 'HN'),
('HUN', 'Hungary', 'HU'),
('ISL', 'Iceland', 'IS'),
('IND', 'India', 'IN'),
('IDN', 'Indonesia', 'ID'),
('IRN', 'Iran', 'IR'),
('IRQ', 'Iraq', 'IQ'),
('IRL', 'Ireland', 'IE'),
('ISR', 'Israel', 'IL'),
('ITA', 'Italy', 'IT'),
('JAM', 'Jamaica', 'JM'),
('JPN', 'Japan', 'JP'),
('JOR', 'Jordan', 'JO'),
('KAZ', 'Kazakhstan', 'KZ'),
('KEN', 'Kenya', 'KE'),
('KIR', 'Kiribati', 'KI'),
('PRK', "Korea, Democratic People's Republic of", 'KP'),
('KOR', 'Korea, Republic of', 'KR'),
('KWT', 'Kuwait', 'KW'),
('KGZ', 'Kyrgyzstan', 'KG'),
('LAO', "Lao People's Democratic Republic", 'LA'),
('LVA', 'Latvia', 'LV'),
('LBN', 'Lebanon', 'LB'),
('LSO', 'Lesotho', 'LS'),
('LBR', 'Liberia', 'LR'),
('LBY', 'Libya', 'LY'),
('LIE', 'Liechtenstein', 'LI'),
('LTU', 'Lithuania', 'LT'),
('LUX', 'Luxembourg', 'LU'),
('MDG', 'Madagascar', 'MG'),
('MWI', 'Malawi', 'MW'),
('MYS', 'Malaysia', 'MY'),
('MDV', 'Maldives', 'MV'),
('MLI', 'Mali', 'ML'),
('MLT', 'Malta', 'MT'),
('MHL', 'Marshall Islands', 'MH'),
('MRT', 'Mauritania', 'MR');